# The URL the site will be built for
base_url = "https://hashedone.github.io"

title = "Hashed devlog"
default_language = "en"

compile_sass = true
build_search_index = true
minify_html = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
render_emoji = true

[extra]
# Put all your custom variables here
